### ISSUE TITLE
Question on the encoder model

### ISSUE THREAD

**Issue by sappho192** [akpe12/JP-KR-ocr-translator-for-travel#2]
Hi, I have another question about your code.

In the `Training.ipynb`, it seems that you've chosen `xlm-roberta-base` model as an encoder. However in the usage code (in `README.md`), the encoder model is `cl-tohoku/bert-base-japanese-v2`.
Did you choose `bert-base-japanese-v2` since its BLUE score is better than the `xlm-roberta-base`?

**Comment by akpe12** [comment]
Hi again @sappho192 , and thank you for having interest in my model!

In a nutshell, you are right exactly.
Our original translator has two translation models. So, as you can see in my readme.md, there are BLEU scores of model1 and model2. Model 1 has cl-tohoku/bert-base-japanese-v2 and model 2 has xlm-roberta-base. Because we wanted to check the performance of encoder models between encoder model trained single language and multi-lingual encoder model.

I hope my explanation was helpful.

**Comment by sappho192** [comment]
Thank you @akpe12 for the detailed explanation.

And I want to let you know that I've added credit for your training code in my repository: https://github.com/sappho192/ffxiv-ja-ko-translator/blob/main/training.ipynb

Your project really helped me to begin my project! ☺🤗

Live long and prosper 🖖
